//
// Generated file, do not edit! Created by opp_msgc 4.1 from AimsunApplPkt.msg.
//

#ifndef _AIMSUNAPPLPKT_M_H_
#define _AIMSUNAPPLPKT_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>AimsunApplPkt.msg</tt> by opp_msgc.
 * <pre>
 * packet AimsunApplPkt
 * {
 *     int destAddr = -1; 
 *     int srcAddr = -1; 
 *     int aimsunId = -1;
 * }
 * </pre>
 */
class AimsunApplPkt : public ::cPacket
{
  protected:
    int destAddr_var;
    int srcAddr_var;
    int aimsunId_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const AimsunApplPkt&);

  public:
    AimsunApplPkt(const char *name=NULL, int kind=0);
    AimsunApplPkt(const AimsunApplPkt& other);
    virtual ~AimsunApplPkt();
    AimsunApplPkt& operator=(const AimsunApplPkt& other);
    virtual AimsunApplPkt *dup() const {return new AimsunApplPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr_var);
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr_var);
    virtual int getAimsunId() const;
    virtual void setAimsunId(int aimsunId_var);
};

inline void doPacking(cCommBuffer *b, AimsunApplPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, AimsunApplPkt& obj) {obj.parsimUnpack(b);}


#endif // _AIMSUNAPPLPKT_M_H_
